name: Android CI

on:
  push:
    branches:
      - 'v**'
      - '!master'
      - '!dev_**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_TOKEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_TOKEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.MAVEN_GPG_KEY_ID }}
      SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    steps:
      - name: "Checkout@V3"
        uses: actions/checkout@v3
      - name: "Setup JDK 11"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: "Publish ComposeExpandableText"
        run: ./gradlew clean assembleRelease androidJavaDocJar androidSourcesJar generatePomFileForNexusPublication publishNexusPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository