name: Android CI

on:
  push:
    branches:
      - 'v**'
      - '!master'
      - '!dev_**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_TOKEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_TOKEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.MAVEN_GPG_KEY_ID }}
      SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    steps:
      - name: "Checkout@V3"
        uses: actions/checkout@v3
      - name: "Setup JDK 11"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean with Gradle
        run: ./gradlew clean

      - name: ReleaseTask
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body:  |
            ### 注意
            - 该库能力只提供：**可折叠的组合项Text**，使用方式如下：
            ```
              ExpandableText(
                modifier = Modifier
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
                .fillMaxWidth(),
                text = buildAnnotatedString { append("请输入你的超长文本，来吧展示，省略更多内容...") },
                textStyle = TextStyle(color = Color.Black, fontSize = 14.sp),
                expandStateText = "展开",
                collapseStateText = "收起"
              )
            ```
          token: ${{ secrets.github_token }}
          commit: master
          tag: ${{ github.ref_name }}

      - name: "Publish ComposeExpandableText"
        run: ./gradlew clean assembleRelease androidJavaDocJar androidSourcesJar generatePomFileForNexusPublication publishNexusPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository